spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "http://266523106449-pojfcjr5r4gtmlontuhfuc3ram9a54l7.apps.googleusercontent.com"
            client-secret: "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"
